web/artifacts/urls.py
from django.urls import path

from . import views

app_name = 'artifacts'
urlpatterns =[ 
    path('', views.IndexView.as_view(), name='index'),        
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),        
]

web/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns =[ 
    path('', views.IndexView.as_view(), name='index'),        
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),        
]

web/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('artifacts/', include('artifacts.urls')),
    path('blog/', include('blog.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('', views.TemplateView.as_view(), name='index'),        
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns =[ 
    path('', views.IndexView.as_view(), name='index'),        
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),        
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),        
    path('<int:question_id>/vote/', views.vote, name='vote'),        
]

web/artifacts/models.py
import datetime
import os

from django.db import models
from django.utils import timezone


class Artifact(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    pub_date = models.DateTimeField('date published', default=timezone.now())

    def __str__(self):
        return self.name


class Picture(models.Model):
    artifact = models.ForeignKey(Artifact, on_delete=models.CASCADE)
    filename = models.CharField(max_length=100)
    image = models.ImageField()

web/blog/models.py
import datetime

from django.db import models
from django.utils import timezone

class Article(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.title

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

web/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

web/polls/forms.py
from django import forms

class PollForm(forms.form):

web/aquanautix/views.py
from django.views import generic

from .models import Artifact


class IndexView(generic.ListView):
    model = Artifact
    template_name = 'aquanautix/index.html'
    context_object_name = 'artifact_list'


class DetailView(generic.DetailView):
    model = Artifact
    template_name = 'aquanautix/detail.html'

web/artifacts/views.py
from django.views import generic

from .models import Artifact


class IndexView(generic.ListView):
    model = Artifact
    template_name = 'artifacts/index.html'
    context_object_name = 'artifact_list'


class DetailView(generic.DetailView):
    model = Artifact
    template_name = 'artifacts/detail.html'

web/blog/views.py
from django.shortcuts import render
from django.views import generic


from .models import Article


class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'latest_article_list'

    def get_queryset(self):
        return Article.objects.order_by('-pub_date')


class DetailView(generic.DetailView):
    model = Article
    template_name = 'blog/detail.html'

web/mysite/views.py
from django.views import generic


class TemplateView(generic.base.TemplateView):
    template_name = 'mysite/index.html'
 

web/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

web/aquanautix/templates/aquanautix/detail.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="col-sm-8">
    <div class="col-sm-4">
        <h1>{{ artifact.name }}</h1>
        <h6>{{ artifact.pub_date }}</h6>
        <p>{{ artifact.description }}</p>
    </div>
    <div class="col-sm-4">
        {% for picture in artifact.picture_set.all %}
            <img src="{{ picture.image.url }}">
    </div>
    {% endfor %}
</div>
{% endblock %}

web/aquanautix/templates/aquanautix/index.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap3 %}

{% block content %}
<div class="col-sm-8">
    <h3>Artifacts</h3>
    {% if artifact_list %}
        {% for artifact in artifact_list %}
        <div class="col-sm-8">
            <div class="col-sm-4">
                <a href="{% url 'artifacts:detail' artifact.id %}">
                    <img src="{{ artifact.picture_set.first.image.url }}" width="100%">
                </a>
            </div>
            <div class="col-sm-4">
                <a href="{% url 'artifacts:detail' artifact.id %}">{{ artifact.name }}</a>
            </div>
        </div>
        {% endfor %}
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
</div>
{% endblock %}

web/artifacts/templates/artifacts/detail.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="col-sm-8">
    <div class="col-sm-8">
        <h1>{{ artifact.name }}</h1>
        <h6>{{ artifact.pub_date }}</h6>
        <p>{{ artifact.description }}</p>
    </div>
    <div class="col-sm-8">
        {% for picture in artifact.picture_set.all %}
        <div class="col-sm">
            <img src="{{ picture.image.url }}">
            {{ picture.image.url }}
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

web/artifacts/templates/artifacts/index.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap3 %}

{% block content %}
<div class="col-sm-8">
    <h3>Artifacts</h3>
    {% if artifact_list %}
        {% for artifact in artifact_list %}
        <div class="col-sm-8">
            <div class="col-sm-4">
                <a href="{% url 'artifacts:detail' artifact.id %}">
                    <img src="{{ artifact.picture_set.first.image.url }}" width="100%">
                </a>
            </div>
            <div class="col-sm-4">
                <a href="{% url 'artifacts:detail' artifact.id %}">{{ artifact.name }}</a>
            </div>
        </div>
        {% endfor %}
    {% else %}
    <p>No artifacts are available.</p>
    {% endif %}
</div>
{% endblock %}

web/blog/templates/blog/detail.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="col-sm-8">
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <h1>{{ article.title }}</h1>
    <h6>{{ article.pub_date }}</h6>
    <p>{{ article.content }}</p>
</div>

{% endblock %}

web/blog/templates/blog/index.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap3 %}

{% block content %}
<div class="col-sm-8">
    <h3>Blog</h3>
    {% if latest_article_list %}
        {% for article in latest_article_list %}
        <div><a href="{% url 'blog:detail' article.id %}">{{ article.title }}</a></div>
        {% endfor %}
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
</div>
{% endblock %}

web/polls/templates/polls/detail.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="col-sm-8">
    <h1>{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
        <input type="submit" value="Vote">
    </form>
</div>
{% endblock %}

web/polls/templates/polls/index.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap3 %}

{% block content %}
<div class="col-sm-8">
    <h3>Polls</h3>
    {% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
</div>
{% endblock %}

web/polls/templates/polls/results.html
{% extends "base.html" %}

{% block content %}
<div class="col-sm-8">
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</div>
{% endblock %}

web/templates/base.html
{% load static %}
{% load bootstrap3 %}

<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylsheet" href="{% static 'css/main.css' %}">
    </head>
    <body>
        <div class="container">
            <div class="row">
                {% include "sidebar.html" %}
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </body>
    <footer>
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </footer>
</html>

web/templates/mysite/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h3>Home</h3>
{% endblock %}

web/templates/sidebar.html
<div class="col-sm-4">
    <div><a href="{% url 'index' %}">Home</a></div>
    <div><a href="{% url 'admin:index' %}">Admin</a></div>
    <div><a href="{% url 'polls:index' %}">Polls</a></div>
    <div><a href="{% url 'blog:index' %}">Blog</a></div>
    <div><a href="{% url 'artifacts:index' %}">Artifacts</a></div>
</div>